# -*- coding: utf-8 -*-
"""PROJECT1U.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lw2VsEeDpey_dPoUoyvRdrUHQgsJfq-
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data= pd.read_csv("/content/ecommerce_data.csv")#to load data set
data.head()#for display 1st 5 row

data.dtypes

data.shape

data.drop('customer_id', axis=1, inplace=True)
data.drop('name', axis=1, inplace=True)

data.drop('email', axis=1, inplace=True)

# """
# Feature Engineering

# Date columns are converted into numerical features
# that represent customer activity and recency.
# """
if 'signup_date' in data.columns:

    date_cols = [
        'signup_date',
        'first_order_date',
        'last_order_date',
        'first_session_date',
        'last_session_date'
    ]

    for col in date_cols:
        data[col] = pd.to_datetime(data[col])

    reference_date = max(
        data['last_order_date'].max(),
        data['last_session_date'].max()
    )

    data['customer_age_days'] = (
        reference_date - data['signup_date']
    ).dt.days

    data['days_since_first_order'] = (
        reference_date - data['first_order_date']
    ).dt.days

    data['days_since_last_order'] = (
        reference_date - data['last_order_date']
    ).dt.days

    data['days_since_first_session'] = (
        reference_date - data['first_session_date']
    ).dt.days

    data['days_since_last_session'] = (
        reference_date - data['last_session_date']
    ).dt.days

    data.drop(
        columns=date_cols,
        inplace=True
    )

data.isna().sum()

"""missing value handling"""

data.columns

cat_cols = [
    'country',
    'age_group',
    'preferred_payment',
    'preferred_device_ord',
    'preferred_source',
    'top_category_bought',
    'preferred_device_sess',
    'preferred_source_sess'
]

for col in cat_cols:
    data[col] = data[col].fillna(data[col].mode()[0])

#avg_rating_given plootting histogram to find whether to take the mode,median or mean(due to the dtype is float)
plt.hist(data['avg_rating_given'])
plt.title('Distribution of avg_rating_given')

plt.show()

#due to left skew we take median here
data['avg_rating_given']=data['avg_rating_given'].fillna(data['avg_rating_given'].median())

#days_since_first_order plootting histogram to find whether to take the mode,median or mean(due to the dtype is float)
plt.hist(data['days_since_first_order'])
plt.title('Distribution of days_since_first_order')

plt.show()

data['days_since_first_order']=data['days_since_first_order'].fillna(data['days_since_first_order'].median())

#days_since_last_order plotting histogram to find whether to take the mode,median or mean(due to the dtype is float)
plt.hist(data['days_since_last_order'])
plt.title('Distribution of days_since_last_order')

plt.show()

data['days_since_last_order']=data['days_since_last_order'].fillna(data['days_since_last_order'].median())

#days_since_first_session plotting histogram to find whether to take the mode,median or mean(due to the dtype is float)
plt.hist(data['days_since_first_session'])
plt.title('Distribution of days_since_first_session')

plt.show()

data['days_since_first_session']=data['days_since_first_session'].fillna(data['days_since_first_session'].median())

#days_since_last_session plotting histogram to find whether to take the mode,median or mean(due to the dtype is float)
plt.hist(data['days_since_last_session'])
plt.title('Distribution of days_since_last_session')

plt.show()

data['days_since_last_session']=data['days_since_last_session'].fillna(data['days_since_last_session'].median())

"""Outliers"""

plt.boxplot(data['age'])
plt.title('box plot of age')
plt.show()

plt.boxplot(data['total_orders'])
plt.title('box plot of total_orders')
plt.show()



plt.boxplot(data['total_spend_usd'])
plt.title('box plot of total_spend_usd')
plt.show()
#not removing outlier due to this is our target

print(data['total_spend_usd'].skew())

# That's a highly right-skewed distribution.This is normal in e-commerce Many customers spend a little
# Few customers spend a lot
#Instead of removing high spenders:

data['total_spend_log'] = np.log1p(data['total_spend_usd'])

plt.boxplot(data['avg_order_value'])
plt.title('box plot of avg_order_value')
plt.show()

print(data['avg_order_value'].describe())

print(data['avg_order_value'].nlargest(10))

"""Although boxplot analysis identified potential outliers in avg_order_value, these values were retained because they represent legitimate high-value customer purchases rather than data entry errors."""

plt.boxplot(data['avg_discount_pct'])
plt.title('box plot of avg_discount_pct')
plt.show()

plt.boxplot(data['avg_rating_given'])
plt.title('box plot of avg_rating_given')
plt.show()

print(data['total_sessions'].describe())
print(data['total_sessions'].nlargest(10))

"""The "outliers" in avg_rating_given is:

Realistic
Business-relevant
Potentially important for predicting spending
"""

plt.boxplot(data['total_sessions'])
plt.title('box plot of total_sessions')
plt.show()

plt.boxplot(data['age'])
plt.title('Box Plot of Age')
plt.show()

print(data['age'].describe())

plt.boxplot(data['avg_discount_pct'])
plt.title('Box Plot of avg_discount_pct')
plt.show()

print(data['avg_discount_pct'].describe())

plt.boxplot(data['customer_age_days'])
plt.show()

print(data['customer_age_days'].describe())

cols = [
    'days_since_first_order',
    'days_since_last_order',
    'days_since_first_session',
    'days_since_last_session'
]

for col in cols:
    plt.boxplot(data[col])
    plt.title(col)
    plt.show()

    print(data[col].describe())

print(data['avg_discount_pct'].describe())
print(data['avg_discount_pct'].nlargest(10))

data.dtypes

"""Encode"""

print(data['clv_tier'].value_counts())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

label_cols = [
    'age_group',
    'preferred_device_ord',
    'preferred_source',
    'top_category_bought',
    'clv_tier'
]

for col in label_cols:
    data[col] = le.fit_transform(data[col])

data = pd.get_dummies(
    data,
    columns=[
        'country',
        'preferred_payment',
        'preferred_device_sess',
        'preferred_source_sess'
    ],
    drop_first=True,
    dtype=int
)

data['marketing_opt_in'] = data['marketing_opt_in'].astype(int)

X = data.drop(
    ['total_spend_usd', 'total_spend_log', 'clv_tier'],
    axis=1
)

y = data['total_spend_log']

print(X.shape)
print(y.shape)
print(X.dtypes.value_counts())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Going to test all the training method and selecting the best"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = lr.predict(X_test_scaled)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)  # no scaling needed

y_pred_rf = rf.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

print(X.columns.tolist())

"""we find that avg_order_value is the leaking column.
avg_order_value = total_spend_usd ÷ total_orders
So the model can directly reconstruct the target from it. That's why R² is 0.9999.
"""

X = data.drop(columns=['total_spend_usd', 'total_spend_log', 'clv_tier', 'avg_order_value'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

y_pred = lr.predict(X_test_scaled)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)  # no scaling needed

y_pred_rf = rf.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(n_estimators=200, learning_rate=0.05, max_depth=4, random_state=42)
gbr.fit(X_train, y_train)

y_pred_gbr = gbr.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_gbr))
print("MAE:", mean_absolute_error(y_test, y_pred_gbr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_gbr)))

import pandas as pd
import matplotlib.pyplot as plt

importances = pd.Series(gbr.feature_importances_, index=X.columns)
top10 = importances.sort_values(ascending=False).head(10)

print(top10)

top10.sort_values().plot(kind='barh', figsize=(8,5))
plt.title('Top 10 Feature Importances - Gradient Boosting')
plt.xlabel('Importance Score')
plt.tight_layout()
plt.show()

X = data.drop(columns=['total_spend_usd', 'total_spend_log', 'clv_tier', 'avg_order_value', 'total_orders'])
# total_orders and avg_order_value are dropped to prevent data leakage.
# avg_order_value = total_spend_usd / total_orders (directly derived from target)
# total_orders dominates feature importance (0.93) making all other features irrelevant.
# Dropping both results in a more honest model that learns from customer behavior
# and demographics rather than order-based shortcuts.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

y_pred = lr.predict(X_test_scaled)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)  # no scaling needed

y_pred_rf = rf.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

gbr = GradientBoostingRegressor(n_estimators=200, learning_rate=0.05, max_depth=4, random_state=42)
gbr.fit(X_train, y_train)

y_pred_gbr = gbr.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred_gbr))
print("MAE:", mean_absolute_error(y_test, y_pred_gbr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_gbr)))

importances = pd.Series(gbr.feature_importances_, index=X.columns)
top10 = importances.sort_values(ascending=False).head(10)

print(top10)

top10.sort_values().plot(kind='barh', figsize=(8,5))
plt.title('Top 10 Feature Importances - Gradient Boosting')
plt.xlabel('Importance Score')
plt.tight_layout()
plt.show()

"""# has_abandoned_cart is retained despite high feature importance (0.879)
# because it is a legitimate customer behavior feature, not derived from the target.
# In real business, abandoned cart behavior is a strong predictor of purchase intent.
"""

import joblib

joblib.dump(gbr, 'spending_model.pkl')
print("Model saved successfully")

model = joblib.load('spending_model.pkl')
print("Model loaded successfully")

joblib.dump(scaler, 'scaler.pkl')

